#!/usr/bin/env bash
# x-cmd-action/ai/commit — Conventional Commits check/generate

set -euo errexit

: "${INPUT_MODEL:=minimax}"
: "${INPUT_MODE:?mode required (check|generate)}"
: "${INPUT_COMMIT_LIMIT:=50}"   # max commits to check in check mode
: "${INPUT_FAIL_ON_INVALID:=true}"

echo "commit: mode=$INPUT_MODE model=$INPUT_MODEL"

case "$INPUT_MODE" in
  check)
    # ── Validate commits in current branch vs main ──
    # Get commits that are in HEAD but not in origin/main
    COMMITS=$(git log "origin/main..HEAD" --pretty=format:"%H|%s" --max-count="$INPUT_COMMIT_LIMIT" 2>/dev/null || \
              git log "main..HEAD" --pretty=format:"%H|%s" --max-count="$INPUT_COMMIT_LIMIT" 2>/dev/null || \
              echo "")

    if [ -z "$COMMITS" ]; then
      echo "commit: no commits to check"
      exit 0
    fi

    # ── Pattern: Conventional Commits ──
    # type(scope)?: subject
    # feat | fix | docs | style | refactor | perf | test | chore | build | ci | revert
    PATTERN='^(feat|fix|docs|style|refactor|perf|test|chore|build|ci|revert)(\([a-zA-Z0-9_-]+\))?!?: .+'

    INVALID=0
    INVALID_LIST=""
    while IFS='|' read -r hash subject; do
      if ! printf '%s' "$subject" | grep -qE "$PATTERN"; then
        INVALID=$((INVALID + 1))
        INVALID_LIST="${INVALID_LIST}- ${hash:0:7}: ${subject}
"
        echo "commit: INVALID: ${hash:0:7}: $subject"
      else
        echo "commit: OK: ${hash:0:7}: $subject"
      fi
    done <<< "$COMMITS"

    # ── Optional AI review of borderline cases ──
    if [ -n "${INPUT_REVIEW_INVALID:-}" ] && [ "$INVALID" -gt 0 ] && [ -n "${MINIMAX_TOKEN:-}" ]; then
      echo "commit: asking AI to review $INVALID invalid commits"
      PROMPT="Review these commit messages and suggest a Conventional Commits compliant version for each:

$INVALID_LIST

Output format (one per line):
<old-sha>: <new-subject>"

      REVIEW=$(printf '%s' "$PROMPT" | x ai request --model "$INPUT_MODEL" 2>&1) || {
        echo "commit: AI review failed, continuing with raw invalid list"
      }

      if [ -n "$REVIEW" ]; then
        COMMENT_BODY="🤖 **ai commit review**

**$INVALID of $(printf '%s' "$COMMITS" | wc -l | tr -d ' ') commits don't follow Conventional Commits.**

Suggested rewrites:

\`\`\`
$REVIEW
\`\`\`

<sub-Generated by [x-cmd-action/ai](https://github.com/x-cmd-action/ai) · commit sub-command</sub-"

        gh issue comment "${INPUT_PR_NUM:-}" --body "$COMMENT_BODY" 2>/dev/null || \
          echo "commit: failed to post review comment (no PR_NUM?)"
      fi
    fi

    echo "commit: $INVALID invalid commits found"

    if [ "$INVALID" -gt 0 ] && [ "$INPUT_FAIL_ON_INVALID" = "true" ]; then
      echo "commit: failing due to invalid commits"
      exit 1
    fi
    ;;

  generate)
    # ── Generate commit message from staged diff ──
    DIFF=$(git diff --cached 2>/dev/null || git diff 2>/dev/null || echo "")

    if [ -z "$DIFF" ]; then
      echo "commit: no staged changes"
      exit 1
    fi

    # Truncate huge diffs.
    DIFF_LINES=$(printf '%s' "$DIFF" | wc -l | tr -d ' ')
    MAX=2000
    if [ "$DIFF_LINES" -gt "$MAX" ]; then
      DIFF=$(printf '%s' "$DIFF" | head -n "$MAX")
      DIFF="$DIFF

(... truncated)"
    fi

    PROMPT=$(cat <<EOF
Generate a Conventional Commits compliant message for the following diff.

Diff:
\`\`\`diff
$DIFF
\`\`\`

Output EXACTLY in this format (no other text):

<type>(<scope>): <subject>

<body explaining what and why, wrapped at 72 chars>

Rules:
- type: feat | fix | docs | style | refactor | perf | test | chore | build | ci | revert
- scope: optional, in parens, lowercase, no spaces
- subject: imperative mood, no period, < 72 chars
- body: optional, separated by blank line
EOF
)

    echo "commit: calling $INPUT_MODEL..."
    RESPONSE=$(printf '%s' "$PROMPT" | x ai request --model "$INPUT_MODEL" 2>&1) || {
      echo "commit: AI call failed: $RESPONSE"
      exit 1
    }

    # Strip leading/trailing whitespace.
    RESPONSE=$(printf '%s' "$RESPONSE" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

    echo "$RESPONSE" > "$GITHUB_OUTPUT_FILE" 2>/dev/null || echo "$RESPONSE"
    echo "commit: generated: $RESPONSE"
    ;;

  *)
    echo "commit: invalid mode '$INPUT_MODE' (expected: check|generate)"
    exit 1
    ;;
esac

echo "commit: done"