#!/usr/bin/env bash
# x-cmd-action/ai/spec — RFC template + post-mortem generator
#
# NO set -e / set -u / pipefail: x-cmd source-loads `x` as a shell
# function that may `exit 1` internally — strict modes get the script
# killed by sourced functions instead of surfacing errors. Explicit
# checks and ${VAR:-defaults} are used instead.

# Resolve action dir robustly.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
: "${ACTION_PATH:=$SCRIPT_DIR}"

# The x-cmd-action/x-cmd step only installs x-cmd onto disk; each `run`
# step is a fresh shell, so the `x` function must be sourced here.
if [ ! -f "$HOME/.x-cmd.root/X" ]; then
  echo "spec: ERROR — x-cmd not installed at $HOME/.x-cmd.root/X" >&2
  exit 1
fi
. "$HOME/.x-cmd.root/X" || { echo "spec: ERROR — failed to source x-cmd" >&2; exit 1; }
command -v x >/dev/null 2>&1 || { echo "spec: ERROR — 'x' unavailable" >&2; exit 1; }

: "${INPUT_MODE:?mode required (rfc|postmortem)}"
: "${ISSUE_NUM:?ISSUE_NUM required}"

echo "spec: mode=$INPUT_MODE issue=#$ISSUE_NUM"

# ── Fetch issue + comments ──
ISSUE_JSON=$(gh api "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUM" \
  --jq '{title: .title, body: .body, labels: [.labels[].name], state: .state}' 2>/dev/null) || {
  echo "spec: failed to fetch issue #$ISSUE_NUM"
  exit 1
}

TITLE=$(printf '%s' "$ISSUE_JSON" | jq -r '.title // ""' 2>/dev/null || echo "")
BODY=$(printf '%s' "$ISSUE_JSON" | jq -r '.body // ""' 2>/dev/null || echo "")
LABELS=$(printf '%s' "$ISSUE_JSON" | jq -r '.labels | join(", ")' 2>/dev/null || echo "")
STATE=$(printf '%s' "$ISSUE_JSON" | jq -r '.state // ""' 2>/dev/null || echo "")

if [ "$INPUT_MODE" = "postmortem" ] && [ "$STATE" != "closed" ]; then
  echo "spec: WARNING — issue is not closed (state=$STATE). Post-mortem typically for closed bugs."
fi

COMMENTS=$(gh api "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUM/comments?per_page=50" \
  --jq '[.[] | {user: .user.login, body: .body}]' 2>/dev/null || echo '[]')

SOURCE="Issue #$ISSUE_NUM: $TITLE
Labels: $LABELS
State: $STATE

Body:
$BODY

Comments:
$COMMENTS"

# ── Delegate to `x ai spec` (RFC / post-mortem templates are built in) ──
echo "spec: calling x ai spec..."
RC=0
RESPONSE=$(printf '%s' "$SOURCE" | x ai spec --mode "$INPUT_MODE" -) || RC=$?
if [ "$RC" != "0" ] || [ -z "$RESPONSE" ]; then
  echo "spec: AI call failed (rc=$RC) — see stderr output above"
  exit 1
fi

# ── Post comment ──
COMMENT_BODY="🤖 **ai spec** (\`$INPUT_MODE\`)

$RESPONSE

---
<sub>Generated by [x-cmd-action/ai](https://github.com/x-cmd-action/ai) · spec sub-command</sub>"

gh issue comment "$ISSUE_NUM" --body "$COMMENT_BODY" && \
  echo "spec: posted RFC/post-mortem as issue comment"

# ── Optional: save to file ──
if [ -n "${INPUT_FILE:-}" ]; then
  printf '%s\n' "$RESPONSE" > "$INPUT_FILE"
  echo "spec: also written to $INPUT_FILE"
fi

echo "spec: done"
