#!/usr/bin/env bash
# x-cmd-action/ai/spec — RFC template + post-mortem generator

set -euo errexit

: "${INPUT_MODEL:=minimax}"
: "${INPUT_MODE:?mode required (rfc|postmortem)}"
: "${ISSUE_NUM:?ISSUE_NUM required}"

echo "spec: mode=$INPUT_MODE issue=#$ISSUE_NUM model=$INPUT_MODEL"

# ── Fetch issue + comments ──
ISSUE_JSON=$(gh api "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUM" \
  --jq '{title: .title, body: .body, labels: [.labels[].name], state: .state}')

TITLE=$(printf '%s' "$ISSUE_JSON" | jq -r '.title')
BODY=$(printf '%s' "$ISSUE_JSON" | jq -r '.body // ""')
LABELS=$(printf '%s' "$ISSUE_JSON" | jq -r '.labels | join(", ")')
STATE=$(printf '%s' "$ISSUE_JSON" | jq -r '.state')

COMMENTS=$(gh api "repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUM/comments?per_page=50" \
  --jq '[.[] | {user: .user.login, body: .body}]')

# ── Build prompt based on mode ──
case "$INPUT_MODE" in
  rfc)
    PROMPT=$(cat <<EOF
Generate an RFC (Request for Comments) document from this feature request issue.

Issue #$ISSUE_NUM: $TITLE
Labels: $LABELS
State: $STATE

Body:
$BODY

Comments:
$COMMENTS

Use this exact RFC template:

# RFC: <Title>

## Summary
<one paragraph: what and why>

## Motivation
<why is this needed? what problem does it solve?>

## Detailed Design
<how will it work? APIs, data flow, edge cases>

## Alternatives Considered
<what other approaches were considered? why not?>

## Drawbacks
<what are the downsides? risks?>

## Open Questions
<what needs further discussion?>

## Unresolved Questions
<what doesn't have a clear answer yet?>
EOF
)
    ;;

  postmortem)
    if [ "$STATE" != "closed" ]; then
      echo "spec: WARNING — issue is not closed (state=$STATE). Post-mortem typically for closed bugs."
    fi

    PROMPT=$(cat <<EOF
Generate a structured post-mortem document from this closed bug issue.

Issue #$ISSUE_NUM: $TITLE
Labels: $LABELS
State: $STATE

Body:
$BODY

Comments (likely contains debugging + fix discussion):
$COMMENTS

Use this exact post-mortem template:

# Post-Mortem: <Title>

## Summary
<one paragraph: what broke and the impact>

## Timeline
<bulleted chronology: when reported, when fixed, when deployed — extract from comments>

## Root Cause
<what actually caused the bug? technical detail>

## Detection
<how was it caught? user report, monitoring, CI?>

## Resolution
<how was it fixed? what changed?>

## Lessons Learned
<what did we learn? what should we do differently?>

## Action Items
<bulleted list of follow-ups: tests, monitoring, docs, refactors>
EOF
)
    ;;

  *)
    echo "spec: invalid mode '$INPUT_MODE' (expected: rfc|postmortem)"
    exit 1
    ;;
esac

# ── Call AI ──
echo "spec: calling $INPUT_MODEL..."
RESPONSE=$(printf '%s' "$PROMPT" | x ai request --model "$INPUT_MODEL" 2>&1) || {
  echo "spec: AI call failed: $RESPONSE"
  exit 1
}

# ── Post comment ──
COMMENT_BODY=$(cat <<EOF
🤖 **ai spec** (\`$INPUT_MODE\`, \`$INPUT_MODEL\`)

$RESPONSE

---
<sub-Generated by [x-cmd-action/ai](https://github.com/x-cmd-action/ai) · spec sub-command</sub-"
EOF
)

gh issue comment "$ISSUE_NUM" --body "$COMMENT_BODY"

echo "spec: posted RFC/post-mortem as issue comment"

# ── Optional: save to file ──
if [ -n "${INPUT_FILE:-}" ]; then
  printf '%s\n' "$RESPONSE" > "$INPUT_FILE"
  echo "spec: also written to $INPUT_FILE"
fi

echo "spec: done"